feat(docs): add spanish translation for glossary page
edenia/tikuna pull request #123
Opened 2022-11-14 23:40 UTC by hanakoori01

### What does this PR do ?

- Resolves adds new spanish definitions to glossary page

### Steps to test 
1. Run `yarn build`
2. Run `yarn start`
3. Go to `localhost:3000`
4. Go to Glossary page

2022-11-15 15:57 UTC, xavier506 commented on docs/i18n/es/docusaurus-plugin-content-docs/current/research/glossary.md
> +### Cuenta
Cuenta deberia estar bajo la `C`

2022-11-15 15:57 UTC, xavier506 commented on docs/i18n/es/docusaurus-plugin-content-docs/current/research/glossary.md
> +### Dirección
place under `D`

2022-11-16 20:30 UTC, kuronosec requested changes

2022-11-16 20:30 UTC, kuronosec commented on docs/i18n/es/docusaurus-plugin-content-docs/current/research/glossary.md
>  Backend es la capa de acceso a datos de un software, que no es directamente accesible por los usuarios,contiene la lógica de la aplicación que maneja dichos datos. El Backend accede al servidor, que
I would change "navegador" for a more generic term "software cliente"

2022-11-16 20:31 UTC, kuronosec commented on docs/i18n/es/docusaurus-plugin-content-docs/current/research/glossary.md
>  Las billeteras son clientes que almacenan llaves privadas asociadas con los permisos de una o más cuentas. Idealmente, una billetera tiene un estado bloqueado (encriptado) y desbloqueado (sin encript
Encriptado ==> Cifrado

2022-11-16 20:32 UTC, kuronosec commented on docs/i18n/es/docusaurus-plugin-content-docs/current/research/glossary.md
> +Una lista negra es una medida que un nodo de la cadena de bloques puede poner en práctica para impedir que bloquee cualquier transacción que haya sido autorizada por una lista definida de cuentas blo
Not clear to me, too confusing

2022-11-16 20:33 UTC, kuronosec commented on docs/i18n/es/docusaurus-plugin-content-docs/current/research/glossary.md
>  Es una lista creciente de registros, llamados bloques, que están vinculados mediante criptografía. Cada bloque contiene un hash criptográfico del bloque anterior, una marca de tiempo y datos de trans
de transacciones

2022-11-16 20:34 UTC, kuronosec commented on docs/i18n/es/docusaurus-plugin-content-docs/current/research/glossary.md
>  Los bloques son archivos donde los datos pertenecientes a la cadena de bloques se registran de forma permanente. Almacenan algunas o todas las transacciones más recientes que aún no han ingresado a n
archivos --> conjuntos de registros

2022-11-16 20:37 UTC, kuronosec commented on docs/i18n/es/docusaurus-plugin-content-docs/current/research/glossary.md
> +Un estado instantáneo de todos los saldos y datos en un momento determinado en la cadena de bloques, que generalmente se refiere a la condición en un bloque específico.
Don't use "Estado" as the beginning of the definition of the word "Estado"

2022-11-16 21:06 UTC, kuronosec commented on docs/i18n/es/docusaurus-plugin-content-docs/current/research/glossary.md
>  Las `Wallets` son clientes que almacenan llaves privadas asociadas con los permisos de una o más cuentas. Idealmente, una billetera tiene un estado bloqueado (encriptado) y desbloqueado (sin encripta
Cifrado

2022-11-16 21:07 UTC, kuronosec commented on docs/i18n/es/docusaurus-plugin-content-docs/current/research/glossary.md
> +Un nodo es responsable de almacenar datos, ejecutar transacciones y agregar nuevos bloques a la cadena de bloques en un sistema de prueba de participación. Para que el software de validación se activ
apostar --> depositar en la cadena

2022-11-16 21:08 UTC, kuronosec commented on docs/i18n/es/docusaurus-plugin-content-docs/current/research/glossary.md
> +The reserve price for each block is known as the "base fee." It is the minimum gas fee a user must pay for a transaction to be included in the subsequent block.
This is in English

2022-11-18 16:25 UTC, kuronosec commented on docs/i18n/es/docusaurus-plugin-content-docs/current/research/glossary.md
> +
This a name, don't traslate it

2022-11-22 16:57 UTC, kuronosec approved these changes
LGTM

2022-11-22 17:04 UTC, merged