Add the page of state of the art
edenia/tikuna pull request #76
Opened 2022-10-26 23:37 UTC by fagomezra

### Title
Add the page of state of the art
### What does this PR do?
Add the page of state of the art
### Steps to test
1. Run yarn build
2. Run yarn start
3. Go to localhost:3000
4. Go to Monitoring > Deploys the links at .md pages.

#### CheckList
- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

2022-10-26 23:43 UTC, kuronosec requested changes

2022-10-26 23:43 UTC, kuronosec commented on docs/docs/research/references.md
>  - [https://ieeexplore.ieee.org/document/9644904](https://ieeexplore.ieee.org/document/9644904)
@fagomezra we should be consistent with formast of the references, with number without numbers?

2022-10-26 23:47 UTC, fagomezra commented on docs/docs/research/references.md
>  - [https://ieeexplore.ieee.org/document/9644904](https://ieeexplore.ieee.org/document/9644904)
yes

2022-10-26 23:50 UTC, xavier506 commented on docs/docs/research/stateoftheart.md
> +---
is this needed ?

2022-10-26 23:57 UTC, xavier506 commented on docs/docs/research/references.md
> +- [2]https://ethereum.org/669c9e2e2027310b6b3cdce6e1c52962/Ethereum_Whitepaper_-_Buterin_2014.pdf
```
- [1] h
- [2]h
```

some numbers have spacing some don't we should keep them consistent

2022-10-26 23:57 UTC, fagomezra commented on docs/docs/research/stateoftheart.md
> +---
Nop, I already deleted them

2022-10-26 23:59 UTC, fagomezra commented on docs/docs/research/references.md
> +- [2]https://ethereum.org/669c9e2e2027310b6b3cdce6e1c52962/Ethereum_Whitepaper_-_Buterin_2014.pdf
I already add the spaces for all lines.

2022-10-27 00:02 UTC, kuronosec approved these changes
LGTM

2022-10-27 00:02 UTC, merged